In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [10]:
features = torch.normal(0, 0.01, (30, 20))
features.unsqueeze(1).unsqueeze(3).shape

torch.Size([30, 1, 20, 1])

In [4]:
from data_process import read_feature

vec = read_feature('resources', 1, selected_indices=None, question_no=None)

In [41]:
vec = read_feature('resources', 1, selected_indices=None, question_no=2)

array(['4.305408e-01', '0.000000e+00', '2.130977e-01', ...,
       '4.241782e-03', '7.900000e+01', '2.831000e+01'], dtype='<U19')

In [8]:
x = np.array(([1, 2, 3]))
print(str(list(x)))

[1, 2, 3]


In [10]:
feature_filename = f'audio_feature{int2str(1)}.txt'
txt_path = os.path.join('resources', feature_filename)
with open(txt_path) as f:
    vectors = f.readlines()
    del vectors[0:TO_DEL_LINES]
    res = np.array([vector.strip('\n').split(',') for vector in vectors])

In [2]:
str(3).rjust(4, '0')

'0003'

In [4]:
torch.log2(torch.tensor(16.0))

tensor(4.)

In [10]:
# 参照ECA-Net论文改为nn.Module的实现
class ECA(nn.Module):
    def __init__(self, num_channel, b=1, gamma=2):
        super(ECA, self).__init__()
        t = int(abs((np.log2(num_channel) + b) / gamma))
        kernel_size = t if t % 2 else t + 1

        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.conv = nn.Conv1d(1, 1, kernel_size=kernel_size, padding=(kernel_size - 1) // 2, bias=False)

    def forward(self, x):
        # x.shape: (batch_size, channel, height, width) = (N, C, H, W)
        y = self.avg_pool(x)
        y = self.conv(y.squeeze(-1).transpose(-1, -2)).transpose(-1, -2).unsqueeze(-1)
        return x * y.expand_as(x)

In [8]:
x = torch.normal(0, 0.01, (1, 3, 28, 28))
x.shape

torch.Size([1, 3, 28, 28])

In [12]:
F.adaptive_max_pool2d(x, 1).shape

torch.Size([1, 3, 1, 1])

In [11]:
eca = ECA(3)
eca(x).shape

torch.Size([1, 3, 28, 28])

In [2]:
from CNN_torch import SpatialAttention

x = torch.normal(0, 0.01, (29, 20))
SA = SpatialAttention()

SA(x).shape


RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [29, 20]

In [4]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform([1, 1, 1, 1, 0, 0, 0])
y =

array([1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [2]:
from constants import NUM_DEPRESSION, NUM_TRAIN_SUBJECTS

y = torch.Tensor([1 if i <= NUM_DEPRESSION else 0 for i in range(1, NUM_TRAIN_SUBJECTS + 1)])
y.shape

torch.Size([38])

In [3]:
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])


In [6]:
x = [np.array([1, 2, 3]) for _ in range(1, 5)]
x = np.array(x)
torch.tensor(x)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)

In [8]:
a = np.array([1, 0, 1])
b = np.array([1, 1, 0])
(a == b).sum()

1

In [1]:
import numpy as np

x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x.shape)
print(x.)

(2, 2, 2)
[1 2 3 4 5 6 7 8]
